# Even Fibonacci numbers
# Problem 2
# 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci_sequence(max_value)
  n1 = 1
  n2 = 1

  result = [] << n1 << n2
  
  while n1 + n2 < max_value
    n3 = n1 + n2

    n1 = n2
    n2 = n3

    result << n3
  end

  result
end

puts fibonacci_sequence(4000000).select { |n| n % 2 == 0 }.inject(:+)
